### ISSUE TITLE
Goto definition error on php project

### ISSUE THREAD

**Issue by haringsrob** [SuduIDE/ideals#69]
<img width="637" alt="Screenshot 2023-03-24 at 10 44 21" src="https://user-images.githubusercontent.com/866743/227484635-127d0d9e-94b6-4182-8e00-b00c838e89e8.png">

On a php project goto definition fails.

Could you tell me where I could get a better error message? Might be able to look at it myself.

**Comment by haringsrob** [comment]
Started it over rpc there's 2 things:

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NoSuchMethodError: 'com.intellij.lang.documentation.DocumentationTarget com.intellij.lang.documentation.ide.IdeDocumentationTargetProvider.documentationTarget(com.intellij.openapi.editor.Editor, com.intellij.psi.PsiFile, com.intellij.codeInsight.lookup.LookupElement)'
```

```
WARN - #c.j.p.PhpIndex - Invalid Signature '∆n'
```

**Comment by serganch** [comment]
Seams a compatibility issue. What version of PhpStorm are you using?

**Comment by haringsrob** [comment]
I tried both 2022 and 2023 latest versions.

**Comment by serganch** [comment]
Not being compatible with 23 is OK. We're waiting for the release to start adaptation. Not being compatible with 22 is not OK. We'll take a look

**Comment by rmzs0711** [comment]
Hi, @haringsrob
I am trying to repeat this issue on php storm 2022.2.3 and everything works fine for me. Could you please provide the exact version of php storm  and a version of IdeaLS(built from master or one of previous releases) you are using?

**Comment by haringsrob** [comment]
Hey @rmzs0711 I build fresh (from the open pr) and installed onto 2023.1 and now it seems fine.

I guess I may have used a bad java version? I am not at all aware of jetbrains plugin system, sorry for the noice.

**Comment by serganch** [comment]
@haringsrob BTW we started to make releases bound to specific IDEA versions, so you won't have to build all the stuff each time.
